name: Puppeteer Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Generate Coverage Report
        run: npm run test:coverage

      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: reports/test-report.html
